name: Run CICD pipeline for testing 
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      name: Get test project from version control
    - uses: actions/setup-node@v4
      name: Setup NodeJS 22
      with:
        node-version: 22
    - name: Install dependencies
      run: npm ci
    - name: Run the tests
      run: npm run test